# Generated by Django 2.2 on 2021-02-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='Allot',
            field=models.IntegerField(default=100000, editable=False),
        ),
    ]
