# Generated by Django 2.2 on 2021-02-06 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('DOB', models.DateField()),
                ('Mob', models.CharField(max_length=10)),
                ('PAN', models.CharField(max_length=10)),
                ('Address', models.CharField(max_length=20)),
                ('City', models.CharField(max_length=10)),
                ('State', models.CharField(max_length=10)),
            ],
        ),
    ]
