# Generated by Django 2.2 on 2021-02-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApp', '0003_auto_20210206_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='Allot',
            field=models.IntegerField(default=100000, editable=False),
        ),
    ]
