# Generated by Django 2.2 on 2021-02-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApp', '0004_auto_20210206_0636'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLoan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.IntegerField()),
                ('Duration', models.ImageField(upload_to='')),
                ('rate', models.IntegerField()),
                ('Date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='Allot',
            field=models.IntegerField(default=10000),
        ),
    ]
