# Generated by Django 2.2 on 2021-02-06 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApp', '0005_auto_20210206_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userloan',
            name='rate',
        ),
    ]
