# Generated by Django 2.2 on 2021-02-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApp', '0006_remove_userloan_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userloan',
            name='Duration',
            field=models.IntegerField(),
        ),
    ]
