# Generated by Django 2.2 on 2021-02-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoanApp', '0007_auto_20210206_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='userloan',
            name='Pan',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
